version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.11.9-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    ports:
      - "15672:15672"
      - "5672:5672"
  database:
    image: postgres:${POSTGRES_VERSION:-15}
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-tg_bot}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    ports:
      - "5432:5432"
  #    volumes:
  #      - db-data:/var/lib/postgresql/data:rw
#  poller:
#    build: ./poller
#    depends_on:
#      - rabbitmq
#    env_file:
#      - ./poller/.env
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
